CREATE OR REPLACE SCHEMA PIPE;


CREATE OR REPLACE FILE FORMAT HRMS.PIPE.CSV_PIPE_FILEFORMAT
TYPE = CSV
FIELD_DELIMITER = ','
SKIP_HEADER = 0
NULL_IF = ('NULL','Null','null') 
FIELD_OPTIONALLY_ENCLOSED_BY = '"'        
EMPTY_FIELD_AS_NULL = TRUE;


------------------CREATE Stage----------------------------------

CREATE OR REPLACE STAGE HRMS.PIPE.AWS_PIPE_CSV_STAGE
STORAGE_INTEGRATION = AWS_S3_INT
URL = 's3://data-snowflake-integration/snowpipe/'
FILE_FORMAT = HRMS.PIPE.CSV_PIPE_FILEFORMAT



LIST @AWS_PIPE_CSV_STAGE


------------------CREATE PIPE TABLE -----------------

create or replace TABLE HRMS.PIPE.PROPERTY_SALES_AWS(
	SUBURB VARCHAR(50),
	ADDRESS VARCHAR(100),
	TYPE VARCHAR(10),
	PRICE VARCHAR(200),
	METHOD VARCHAR(10),
	SELLERG VARCHAR(50),
	DATE VARCHAR(50),
	DISTANCE VARCHAR(50),
	POSTCODE VARCHAR(50),
	BEDROOM2 VARCHAR(50),
	BATHROOM VARCHAR(50),
	CAR VARCHAR(50),
	LANDSIZE VARCHAR(50),
	BUILDINGAREA VARCHAR(50),
	YEARBUILT VARCHAR(50),
	COUNCILAREA VARCHAR(50),
	LATTITUDE VARCHAR(50),
	LONGTITUDE VARCHAR(50),
	REGIONNAME VARCHAR(50),
	PROPERTYCOUNT VARCHAR(50)
);

----------------------------PIPE (For Real Time Injestion)-----------------------------------


CREATE OR REPLACE PIPE PIPE_PROPERTY_SALES
AUTO_INGEST=TRUE
AS
COPY INTO PROPERTY_SALES_AWS FROM @AWS_PIPE_CSV_STAGE
FILE_FORMAT='CSV_PIPE_FILEFORMAT';


Show pipes Like 'PIPE_PROPERTY_SALES'

ALTER PIPE PIPE_PROPERTY_SALES REFRESH;

SELECT * FROM PROPERTY_SALES_AWS

SELECT * FROM TABLE(INFORMATION_SCHEMA.COPY_HISTORY(
  TABLE_NAME => 'PROPERTY_SALES_AWS',
  START_TIME => DATEADD(hours, -1, CURRENT_TIMESTAMP())));

