CREATE OR REPLACE FILE FORMAT HRMS.SCHEDULE.CSV_PIPE_FILEFORMAT
TYPE = CSV
FIELD_DELIMITER = ','
SKIP_HEADER = 0
NULL_IF = ('NULL','Null','null') 
FIELD_OPTIONALLY_ENCLOSED_BY = '"'        
EMPTY_FIELD_AS_NULL = TRUE;

-----------------------------


CREATE OR REPLACE STORAGE INTEGRATION AWS_S3_INT
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = S3
ENABLED = TRUE 
STORAGE_AWS_ROLE_ARN ='arn:aws:iam::276824024614:role/Snow-Flake-Full-Access-S3'
STORAGE_ALLOWED_LOCATIONS = ('s3://data-snowflake-integration/snowpipe/')

------------------CREATE Stage----------------------------------

CREATE OR REPLACE STAGE HRMS.SCHEDULE.AWS_PIPE_CSV_STAGE
STORAGE_INTEGRATION = AWS_S3_INT
URL = 's3://data-snowflake-integration/snowpipe/'
FILE_FORMAT = HRMS.SCHEDULE.CSV_PIPE_FILEFORMAT

DESC INTEGRATION AWS_S3_INT

LIST @AWS_PIPE_CSV_STAGE


------------------CREATE PIPE TABLE -----------------

create or replace TABLE HRMS.PIPE.PROPERTY_SALES_AWS(
	SUBURB VARCHAR(50),
	ADDRESS VARCHAR(100),
	TYPE VARCHAR(10),
	PRICE VARCHAR(200),
	METHOD VARCHAR(10),
	SELLERG VARCHAR(50),
	DATE VARCHAR(50),
	DISTANCE VARCHAR(50),
	POSTCODE VARCHAR(50),
	BEDROOM2 VARCHAR(50),
	BATHROOM VARCHAR(50),
	CAR VARCHAR(50),
	LANDSIZE VARCHAR(50),
	BUILDINGAREA VARCHAR(50),
	YEARBUILT VARCHAR(50),
	COUNCILAREA VARCHAR(50),
	LATTITUDE VARCHAR(50),
	LONGTITUDE VARCHAR(50),
	REGIONNAME VARCHAR(50),
	PROPERTYCOUNT VARCHAR(50)
);

-------------------CREATE TASKs-------------------------------------------


CREATE or REPLACE SCHEMA Schedule;

CREATE OR REPLACE TASK TASK_CREATE_TABLE  
WAREHOUSE = COMPUTE_WH
SCHEDULE = 'USING CRON 6 15 * * * Asia/Riyadh'  -- Every 10 minutes in Saudi time
AS
BEGIN

    -- Step 1: Truncate the table
    
    TRUNCATE TABLE IF EXISTS SCHEDULE.PROPERTY_SALES_AWS;

    -- Step 2: Insert data from HR.EMPLOYEES
    
    COPY INTO PROPERTY_SALES_AWS FROM  @AWS_PIPE_CSV_STAGE
    FILE_FORMAT='CSV_PIPE_FILEFORMAT'
    ON_ERROR=CONTINUE;

END;

Show TASKS

ALTER TASK TASK_CREATE_TABLE  RESUME;




SELECT *FROM SCHEDULE.PROPERTY_SALES_AWS
WHERE ADDRESS='6 Agnes St'



